# Generated by Django 5.2.3 on 2025-06-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cwr",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("cwr_part_number", models.TextField(blank=True, null=True)),
                ("manufacturer_part_number", models.TextField(blank=True, null=True)),
                ("upc", models.TextField(blank=True, null=True)),
                (
                    "quantity_available_to_ship_combined",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "quantity_available_to_ship_nj",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "quantity_available_to_ship_fl",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "next_shipment_date_combined",
                    models.TextField(blank=True, null=True),
                ),
                ("next_shipment_date_nj", models.TextField(blank=True, null=True)),
                ("next_shipment_date_fl", models.TextField(blank=True, null=True)),
                ("your_cost", models.TextField(blank=True, null=True)),
                ("list_price", models.TextField(blank=True, null=True)),
                ("m_a_p_price", models.TextField(blank=True, null=True)),
                ("m_r_p_price", models.TextField(blank=True, null=True)),
                (
                    "uppercase_title",
                    models.TextField(
                        blank=True, db_column="Uppercase Title", null=True
                    ),
                ),
                ("title", models.TextField(blank=True, db_column="Title", null=True)),
                (
                    "full_description",
                    models.TextField(
                        blank=True, db_column="Full Description", null=True
                    ),
                ),
                ("category_id", models.TextField(blank=True, null=True)),
                (
                    "category_name",
                    models.TextField(blank=True, db_column="Category Name", null=True),
                ),
                ("manufacturer_name", models.TextField(blank=True, null=True)),
                ("shipping_weight", models.TextField(blank=True, null=True)),
                ("box_height", models.TextField(blank=True, null=True)),
                ("box_length", models.TextField(blank=True, null=True)),
                ("box_width", models.TextField(blank=True, null=True)),
                (
                    "list_of_accessories_by_sku",
                    models.TextField(
                        blank=True, db_column="List of Accessories by SKU", null=True
                    ),
                ),
                (
                    "list_of_accessories_by_mfg",
                    models.TextField(
                        blank=True, db_column="List of Accessories by MFG#", null=True
                    ),
                ),
                (
                    "quick_specs",
                    models.TextField(blank=True, db_column="Quick Specs", null=True),
                ),
                (
                    "image_300x300_url",
                    models.TextField(
                        blank=True, db_column="Image (300x300) Url", null=True
                    ),
                ),
                (
                    "image_1000x1000_url",
                    models.TextField(
                        blank=True, db_column="Image (1000x1000) Url", null=True
                    ),
                ),
                ("non_stock", models.TextField(blank=True, null=True)),
                (
                    "drop_ships_direct_from_vendor",
                    models.TextField(blank=True, null=True),
                ),
                ("hazardous_materials", models.TextField(blank=True, null=True)),
                ("truck_freight", models.BooleanField(blank=True, null=True)),
                ("exportable", models.TextField(blank=True, null=True)),
                ("first_class_mail", models.TextField(blank=True, null=True)),
                ("oversized", models.BooleanField(blank=True, null=True)),
                ("remanufactured", models.TextField(blank=True, null=True)),
                ("closeout", models.TextField(blank=True, null=True)),
                ("harmonization_code", models.TextField(blank=True, null=True)),
                ("country_of_origin", models.TextField(blank=True, null=True)),
                ("sale", models.TextField(blank=True, null=True)),
                (
                    "original_price_if_on_sale_closeout",
                    models.TextField(blank=True, null=True),
                ),
                ("sale_start_date", models.TextField(blank=True, null=True)),
                ("sale_end_date", models.TextField(blank=True, null=True)),
                ("rebate", models.TextField(blank=True, db_column="Rebate", null=True)),
                (
                    "rebate_description",
                    models.TextField(
                        blank=True, db_column="Rebate Description", null=True
                    ),
                ),
                ("rebate_start_date", models.TextField(blank=True, null=True)),
                ("rebate_end_date", models.TextField(blank=True, null=True)),
                ("google_merchant_category", models.TextField(blank=True, null=True)),
                (
                    "quick_guide_literature_pdf_url",
                    models.TextField(blank=True, null=True),
                ),
                ("owners_manual_pdf_url", models.TextField(blank=True, null=True)),
                (
                    "brochure_literature_pdf_url",
                    models.TextField(blank=True, null=True),
                ),
                ("installation_guide_pdf_url", models.TextField(blank=True, null=True)),
                (
                    "video_urls",
                    models.TextField(blank=True, db_column="Video Urls", null=True),
                ),
                ("prop_65", models.TextField(blank=True, null=True)),
                (
                    "prop_65_description",
                    models.TextField(
                        blank=True, db_column="Prop 65 Description", null=True
                    ),
                ),
                ("free_shipping", models.TextField(blank=True, null=True)),
                (
                    "free_shipping_end_date",
                    models.TextField(
                        blank=True, db_column="Free Shipping End Date", null=True
                    ),
                ),
                ("returnable", models.BooleanField(blank=True, null=True)),
                (
                    "image_additional_1000x1000_urls",
                    models.TextField(
                        blank=True,
                        db_column="Image Additional (1000x1000) Urls",
                        null=True,
                    ),
                ),
                ("case_qty_nj", models.TextField(blank=True, null=True)),
                ("case_qty_fl", models.TextField(blank=True, null=True)),
                (
                    "number_3rd_party_marketplaces",
                    models.BooleanField(
                        blank=True, db_column="3rd Party Marketplaces", null=True
                    ),
                ),
                ("fcc_id", models.TextField(blank=True, db_column="FCC ID", null=True)),
                ("sku", models.TextField(blank=True, null=True)),
                ("mfgn", models.TextField(blank=True, null=True)),
                ("qty", models.TextField(blank=True, null=True)),
                ("qtynj", models.TextField(blank=True, null=True)),
                ("qtyfl", models.TextField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("map", models.TextField(blank=True, null=True)),
                ("mrp", models.TextField(blank=True, null=True)),
                (
                    "features",
                    models.TextField(blank=True, db_column="Features", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fragrancex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, db_column="SKU", max_length=255, null=True
                    ),
                ),
                (
                    "productName",
                    models.CharField(
                        blank=True, db_column="PRODUCT_NAME", max_length=255, null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, db_column="DESCRIPTION", null=True),
                ),
                (
                    "brandName",
                    models.CharField(
                        blank=True, db_column="BRAND_NAME", max_length=255, null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True, db_column="GENDER", max_length=255, null=True
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, db_column="SIZE", max_length=255, null=True
                    ),
                ),
                (
                    "metric_size",
                    models.CharField(
                        blank=True, db_column="METRIC_SIZE", max_length=255, null=True
                    ),
                ),
                (
                    "retailPriceUSD",
                    models.CharField(
                        blank=True,
                        db_column="RETAIL_PRICE_USD",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "wholesalePriceUSD",
                    models.DecimalField(
                        blank=True,
                        db_column="WHOLESALE_PRICE_USD",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "wholesalePriceEUR",
                    models.CharField(
                        blank=True,
                        db_column="WHOLESALE_PRICE_EUR",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "wholesalePriceGBP",
                    models.CharField(
                        blank=True,
                        db_column="WHOLESALE_PRICE_GBP",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "wholesalePriceCAD",
                    models.CharField(
                        blank=True,
                        db_column="WHOLESALE_PRICE_CAD",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "wholesalePriceAUD",
                    models.CharField(
                        blank=True,
                        db_column="WHOLESALE_PRICE_AUD",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "smallImageUrl",
                    models.CharField(
                        blank=True,
                        db_column="SMALL_IMAGE_URL",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "largeImageUrl",
                    models.CharField(
                        blank=True,
                        db_column="LARGE_IMAGE_URL",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, db_column="TYPE", max_length=255, null=True
                    ),
                ),
                (
                    "quantityAvailable",
                    models.CharField(
                        blank=True,
                        db_column="QUANTITY_AVAILABLE",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "upc",
                    models.CharField(
                        blank=True, db_column="UPC", max_length=255, null=True
                    ),
                ),
                (
                    "instock",
                    models.CharField(
                        blank=True, db_column="INSTOCK", max_length=255, null=True
                    ),
                ),
                (
                    "parentCode",
                    models.CharField(
                        blank=True, db_column="PARENT_CODE", max_length=255, null=True
                    ),
                ),
                (
                    "features",
                    models.TextField(blank=True, db_column="Features", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lipsey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.TextField(blank=True, db_column="Sku", null=True)),
                (
                    "description1",
                    models.TextField(blank=True, db_column="Description1", null=True),
                ),
                (
                    "description2",
                    models.TextField(blank=True, db_column="Description2", null=True),
                ),
                ("upc", models.TextField(blank=True, db_column="Upc", null=True)),
                (
                    "manufacturermodelno",
                    models.TextField(
                        blank=True, db_column="ManufacturerModelNo", null=True
                    ),
                ),
                ("msrp", models.TextField(blank=True, db_column="Msrp", null=True)),
                ("model", models.TextField(blank=True, db_column="Model", null=True)),
                (
                    "calibergauge",
                    models.TextField(blank=True, db_column="CaliberGauge", null=True),
                ),
                (
                    "manufacturer",
                    models.TextField(blank=True, db_column="Manufacturer", null=True),
                ),
                ("type", models.TextField(blank=True, db_column="Type", null=True)),
                ("action", models.TextField(blank=True, db_column="Action", null=True)),
                (
                    "barrellength",
                    models.TextField(blank=True, db_column="BarrelLength", null=True),
                ),
                (
                    "capacity",
                    models.TextField(blank=True, db_column="Capacity", null=True),
                ),
                ("finish", models.TextField(blank=True, db_column="Finish", null=True)),
                (
                    "overalllength",
                    models.TextField(blank=True, db_column="OverallLength", null=True),
                ),
                (
                    "receiver",
                    models.TextField(blank=True, db_column="Receiver", null=True),
                ),
                ("safety", models.TextField(blank=True, db_column="Safety", null=True)),
                ("sights", models.TextField(blank=True, db_column="Sights", null=True)),
                (
                    "stockframegrips",
                    models.TextField(
                        blank=True, db_column="StockFrameGrips", null=True
                    ),
                ),
                (
                    "magazine",
                    models.TextField(blank=True, db_column="Magazine", null=True),
                ),
                ("weight", models.TextField(blank=True, db_column="Weight", null=True)),
                (
                    "imagename",
                    models.TextField(blank=True, db_column="ImageName", null=True),
                ),
                (
                    "chamber",
                    models.TextField(blank=True, db_column="Chamber", null=True),
                ),
                (
                    "drilledandtapped",
                    models.TextField(
                        blank=True, db_column="DrilledAndTapped", null=True
                    ),
                ),
                (
                    "rateoftwist",
                    models.TextField(blank=True, db_column="RateOfTwist", null=True),
                ),
                (
                    "itemtype",
                    models.TextField(blank=True, db_column="ItemType", null=True),
                ),
                (
                    "additionalfeature1",
                    models.TextField(
                        blank=True, db_column="AdditionalFeature1", null=True
                    ),
                ),
                (
                    "additionalfeature2",
                    models.TextField(
                        blank=True, db_column="AdditionalFeature2", null=True
                    ),
                ),
                (
                    "additionalfeature3",
                    models.TextField(
                        blank=True, db_column="AdditionalFeature3", null=True
                    ),
                ),
                (
                    "shippingweight",
                    models.TextField(blank=True, db_column="ShippingWeight", null=True),
                ),
                (
                    "boundbookmanufacturer",
                    models.TextField(
                        blank=True, db_column="BoundBookManufacturer", null=True
                    ),
                ),
                (
                    "boundbookmodel",
                    models.TextField(blank=True, db_column="BoundBookModel", null=True),
                ),
                (
                    "boundbooktype",
                    models.TextField(blank=True, db_column="BoundBookType", null=True),
                ),
                (
                    "nfathreadpattern",
                    models.TextField(
                        blank=True, db_column="NfaThreadPattern", null=True
                    ),
                ),
                (
                    "nfaattachmentmethod",
                    models.TextField(
                        blank=True, db_column="NfaAttachmentMethod", null=True
                    ),
                ),
                (
                    "nfabaffletype",
                    models.TextField(blank=True, db_column="NfaBaffleType", null=True),
                ),
                (
                    "silencercanbedisassembled",
                    models.TextField(
                        blank=True, db_column="SilencerCanBeDisassembled", null=True
                    ),
                ),
                (
                    "silencerconstructionmaterial",
                    models.TextField(
                        blank=True, db_column="SilencerConstructionMaterial", null=True
                    ),
                ),
                (
                    "nfadbreduction",
                    models.TextField(blank=True, db_column="NfaDbReduction", null=True),
                ),
                (
                    "silenceroutsidediameter",
                    models.TextField(
                        blank=True, db_column="SilencerOutsideDiameter", null=True
                    ),
                ),
                (
                    "nfaform3caliber",
                    models.TextField(
                        blank=True, db_column="NfaForm3Caliber", null=True
                    ),
                ),
                (
                    "opticmagnification",
                    models.TextField(
                        blank=True, db_column="OpticMagnification", null=True
                    ),
                ),
                (
                    "maintubesize",
                    models.TextField(blank=True, db_column="MaintubeSize", null=True),
                ),
                (
                    "adjustableobjective",
                    models.TextField(
                        blank=True, db_column="AdjustableObjective", null=True
                    ),
                ),
                (
                    "objectivesize",
                    models.TextField(blank=True, db_column="ObjectiveSize", null=True),
                ),
                (
                    "opticadjustments",
                    models.TextField(
                        blank=True, db_column="OpticAdjustments", null=True
                    ),
                ),
                (
                    "illuminatedreticle",
                    models.TextField(
                        blank=True, db_column="IlluminatedReticle", null=True
                    ),
                ),
                (
                    "reticle",
                    models.TextField(blank=True, db_column="Reticle", null=True),
                ),
                (
                    "exclusive",
                    models.TextField(blank=True, db_column="Exclusive", null=True),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, db_column="Quantity", null=True
                    ),
                ),
                (
                    "allocated",
                    models.TextField(blank=True, db_column="Allocated", null=True),
                ),
                ("onsale", models.TextField(blank=True, db_column="OnSale", null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        db_column="Price",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "currentprice",
                    models.TextField(blank=True, db_column="CurrentPrice", null=True),
                ),
                (
                    "retailmap",
                    models.TextField(blank=True, db_column="RetailMap", null=True),
                ),
                (
                    "fflrequired",
                    models.TextField(blank=True, db_column="FflRequired", null=True),
                ),
                (
                    "sotrequired",
                    models.TextField(blank=True, db_column="SotRequired", null=True),
                ),
                (
                    "exclusivetype",
                    models.TextField(blank=True, db_column="ExclusiveType", null=True),
                ),
                (
                    "scopecoverincluded",
                    models.TextField(
                        blank=True, db_column="ScopeCoverIncluded", null=True
                    ),
                ),
                (
                    "special",
                    models.TextField(blank=True, db_column="Special", null=True),
                ),
                (
                    "sightstype",
                    models.TextField(blank=True, db_column="SightsType", null=True),
                ),
                ("case", models.TextField(blank=True, db_column="Case", null=True)),
                ("choke", models.TextField(blank=True, db_column="Choke", null=True)),
                (
                    "dbreduction",
                    models.TextField(blank=True, db_column="DbReduction", null=True),
                ),
                ("family", models.TextField(blank=True, db_column="Family", null=True)),
                (
                    "finishtype",
                    models.TextField(blank=True, db_column="FinishType", null=True),
                ),
                ("frame", models.TextField(blank=True, db_column="Frame", null=True)),
                (
                    "griptype",
                    models.TextField(blank=True, db_column="GripType", null=True),
                ),
                (
                    "handgunslidematerial",
                    models.TextField(
                        blank=True, db_column="HandgunSlideMaterial", null=True
                    ),
                ),
                (
                    "countryoforigin",
                    models.TextField(
                        blank=True, db_column="CountryOfOrigin", null=True
                    ),
                ),
                (
                    "itemlength",
                    models.TextField(blank=True, db_column="ItemLength", null=True),
                ),
                (
                    "itemwidth",
                    models.TextField(blank=True, db_column="ItemWidth", null=True),
                ),
                (
                    "itemheight",
                    models.TextField(blank=True, db_column="ItemHeight", null=True),
                ),
                (
                    "packagelength",
                    models.TextField(blank=True, db_column="PackageLength", null=True),
                ),
                (
                    "packagewidth",
                    models.TextField(blank=True, db_column="PackageWidth", null=True),
                ),
                (
                    "packageheight",
                    models.TextField(blank=True, db_column="PackageHeight", null=True),
                ),
                (
                    "itemgroup",
                    models.TextField(blank=True, db_column="ItemGroup", null=True),
                ),
                (
                    "features",
                    models.TextField(blank=True, db_column="Features", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rsr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.TextField(blank=True, db_column="SKU", null=True)),
                (
                    "last_modified",
                    models.DateTimeField(
                        blank=True, db_column="Last_Modified", null=True
                    ),
                ),
                ("upc", models.TextField(blank=True, db_column="UPC", null=True)),
                ("title", models.TextField(blank=True, db_column="Title", null=True)),
                (
                    "description",
                    models.TextField(blank=True, db_column="Description", null=True),
                ),
                (
                    "manufacturer_code",
                    models.TextField(
                        blank=True, db_column="Manufacturer_Code", null=True
                    ),
                ),
                (
                    "manufacturer_name",
                    models.TextField(
                        blank=True, db_column="Manufacturer_Name", null=True
                    ),
                ),
                (
                    "manufacturer_part_number",
                    models.TextField(
                        blank=True, db_column="Manufacturer_Part_Number", null=True
                    ),
                ),
                (
                    "department_id",
                    models.TextField(blank=True, db_column="Department_ID", null=True),
                ),
                (
                    "department_name",
                    models.TextField(
                        blank=True, db_column="Department_Name", null=True
                    ),
                ),
                (
                    "category_id",
                    models.TextField(blank=True, db_column="Category_ID", null=True),
                ),
                (
                    "category_name",
                    models.TextField(blank=True, db_column="Category_Name", null=True),
                ),
                (
                    "subcategory_name",
                    models.TextField(
                        blank=True, db_column="Subcategory_Name", null=True
                    ),
                ),
                (
                    "exclusive",
                    models.CharField(
                        blank=True, db_column="Exclusive", max_length=1, null=True
                    ),
                ),
                (
                    "talo_exclusive",
                    models.CharField(
                        blank=True, db_column="Talo_Exclusive", max_length=1, null=True
                    ),
                ),
                (
                    "coming_soon",
                    models.CharField(
                        blank=True, db_column="Coming_Soon", max_length=1, null=True
                    ),
                ),
                (
                    "new_item",
                    models.CharField(
                        blank=True, db_column="New_Item", max_length=1, null=True
                    ),
                ),
                (
                    "le_resale_only",
                    models.CharField(
                        blank=True, db_column="LE_Resale_Only", max_length=1, null=True
                    ),
                ),
                (
                    "unit_of_measure",
                    models.TextField(
                        blank=True, db_column="Unit_of_Measure", null=True
                    ),
                ),
                (
                    "items_per_case",
                    models.IntegerField(
                        blank=True, db_column="Items_Per_Case", null=True
                    ),
                ),
                (
                    "items_per_unit",
                    models.IntegerField(
                        blank=True, db_column="Items_Per_Unit", null=True
                    ),
                ),
                (
                    "units_per_case",
                    models.IntegerField(
                        blank=True, db_column="Units_Per_Case", null=True
                    ),
                ),
                (
                    "nfa",
                    models.CharField(
                        blank=True, db_column="NFA", max_length=1, null=True
                    ),
                ),
                (
                    "hazard_warning",
                    models.TextField(blank=True, db_column="Hazard_Warning", null=True),
                ),
                (
                    "image_count",
                    models.IntegerField(blank=True, db_column="Image_Count", null=True),
                ),
                (
                    "msrp",
                    models.DecimalField(
                        blank=True,
                        db_column="MSRP",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "map",
                    models.DecimalField(
                        blank=True,
                        db_column="MAP",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "inventory_on_hand",
                    models.IntegerField(
                        blank=True, db_column="Inventory_On_Hand", null=True
                    ),
                ),
                (
                    "ground_only",
                    models.CharField(
                        blank=True, db_column="Ground_Only", max_length=1, null=True
                    ),
                ),
                (
                    "drop_ship_block",
                    models.CharField(
                        blank=True, db_column="Drop_Ship_Block", max_length=1, null=True
                    ),
                ),
                (
                    "closeout",
                    models.CharField(
                        blank=True, db_column="Closeout", max_length=1, null=True
                    ),
                ),
                (
                    "allocated",
                    models.CharField(
                        blank=True, db_column="Allocated", max_length=1, null=True
                    ),
                ),
                (
                    "drop_shippable",
                    models.CharField(
                        blank=True, db_column="Drop_Shippable", max_length=1, null=True
                    ),
                ),
                (
                    "unit_weight",
                    models.DecimalField(
                        blank=True,
                        db_column="Unit_Weight",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "unit_length",
                    models.DecimalField(
                        blank=True,
                        db_column="Unit_Length",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "unit_width",
                    models.DecimalField(
                        blank=True,
                        db_column="Unit_Width",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "unit_height",
                    models.DecimalField(
                        blank=True,
                        db_column="Unit_Height",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "case_weight",
                    models.DecimalField(
                        blank=True,
                        db_column="Case_Weight",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "case_length",
                    models.DecimalField(
                        blank=True,
                        db_column="Case_Length",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "case_width",
                    models.DecimalField(
                        blank=True,
                        db_column="Case_Width",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "case_height",
                    models.DecimalField(
                        blank=True,
                        db_column="Case_Height",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "blemished",
                    models.CharField(
                        blank=True, db_column="Blemished", max_length=1, null=True
                    ),
                ),
                (
                    "dealer_price",
                    models.DecimalField(
                        blank=True,
                        db_column="Dealer_Price",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "dealer_case_price",
                    models.DecimalField(
                        blank=True,
                        db_column="Dealer_Case_Price",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "features",
                    models.TextField(blank=True, db_column="Features", null=True),
                ),
                ("images", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ssi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        db_column="SKU",
                        db_index=True,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="Description", max_length=255, null=True
                    ),
                ),
                (
                    "datecreated",
                    models.CharField(
                        blank=True, db_column="DateCreated", max_length=255, null=True
                    ),
                ),
                (
                    "dimensionh",
                    models.CharField(
                        blank=True, db_column="DimensionH", max_length=255, null=True
                    ),
                ),
                (
                    "dimensionl",
                    models.CharField(
                        blank=True, db_column="DimensionL", max_length=255, null=True
                    ),
                ),
                (
                    "dimensionw",
                    models.CharField(
                        blank=True, db_column="DimensionW", max_length=255, null=True
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, db_column="Manufacturer", max_length=255, null=True
                    ),
                ),
                (
                    "imageurl",
                    models.CharField(
                        blank=True, db_column="ImageURL", max_length=255, null=True
                    ),
                ),
                (
                    "thumbnailurl",
                    models.CharField(
                        blank=True, db_column="ThumbnailURL", max_length=255, null=True
                    ),
                ),
                (
                    "upccode",
                    models.CharField(
                        blank=True,
                        db_column="UPCCode",
                        db_index=True,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        blank=True, db_column="Weight", max_length=255, null=True
                    ),
                ),
                (
                    "weightunits",
                    models.CharField(
                        blank=True, db_column="WeightUnits", max_length=255, null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        db_column="Category",
                        db_index=True,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        blank=True, db_column="Subcategory", max_length=255, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, db_column="Status", max_length=255, null=True
                    ),
                ),
                (
                    "map",
                    models.CharField(
                        blank=True, db_column="MAP", max_length=255, null=True
                    ),
                ),
                (
                    "msrp",
                    models.CharField(
                        blank=True, db_column="MSRP", max_length=255, null=True
                    ),
                ),
                (
                    "mpn",
                    models.CharField(
                        blank=True, db_column="MPN", max_length=255, null=True
                    ),
                ),
                (
                    "minimumorderquantity",
                    models.CharField(
                        blank=True,
                        db_column="MinimumOrderQuantity",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "detaileddescription",
                    models.TextField(
                        blank=True, db_column="DetailedDescription", null=True
                    ),
                ),
                (
                    "shippingweight",
                    models.CharField(
                        blank=True,
                        db_column="ShippingWeight",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "shippinglength",
                    models.CharField(
                        blank=True,
                        db_column="ShippingLength",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "shippingwidth",
                    models.CharField(
                        blank=True, db_column="ShippingWidth", max_length=255, null=True
                    ),
                ),
                (
                    "shippingheight",
                    models.CharField(
                        blank=True,
                        db_column="ShippingHeight",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("attribute1", models.TextField(blank=True, null=True)),
                ("attribute2", models.TextField(blank=True, null=True)),
                ("attribute3", models.TextField(blank=True, null=True)),
                ("attribute4", models.TextField(blank=True, null=True)),
                ("attribute5", models.TextField(blank=True, null=True)),
                ("attribute6", models.TextField(blank=True, null=True)),
                ("attribute7", models.TextField(blank=True, null=True)),
                (
                    "prop65warning",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("prop65reason", models.TextField(blank=True, null=True)),
                ("countryoforigin", models.TextField(blank=True, null=True)),
                ("groundshippingrequired", models.TextField(blank=True, null=True)),
                (
                    "price",
                    models.CharField(
                        blank=True, db_column="Price", max_length=255, null=True
                    ),
                ),
                ("avgshipcost", models.TextField(blank=True, null=True)),
                (
                    "qty",
                    models.CharField(
                        blank=True, db_column="Qty", max_length=255, null=True
                    ),
                ),
                (
                    "features",
                    models.TextField(blank=True, db_column="Features", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vendors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("logo", models.ImageField(upload_to="logos/")),
                ("address_street1", models.CharField(max_length=150)),
                ("address_street2", models.CharField(max_length=150, null=True)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("has_data", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Zanders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available", models.CharField(blank=True, max_length=10, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("desc1", models.TextField(blank=True, null=True)),
                ("desc2", models.TextField(blank=True, null=True)),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("mfgpnumber", models.CharField(blank=True, max_length=255, null=True)),
                ("msrp", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "price1",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("price2", models.CharField(blank=True, max_length=10, null=True)),
                ("price3", models.CharField(blank=True, max_length=10, null=True)),
                ("qty1", models.CharField(blank=True, max_length=10, null=True)),
                ("qty2", models.CharField(blank=True, max_length=10, null=True)),
                ("qty3", models.CharField(blank=True, max_length=10, null=True)),
                ("upc", models.CharField(blank=True, max_length=255, null=True)),
                ("weight", models.CharField(blank=True, max_length=10, null=True)),
                ("serialized", models.CharField(blank=True, max_length=10, null=True)),
                ("map", models.CharField(blank=True, max_length=10, null=True)),
                ("imagelink", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "features",
                    models.TextField(blank=True, db_column="Features", null=True),
                ),
            ],
        ),
    ]
