# Generated by Django 5.2.3 on 2025-06-27 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendorActivities", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("ftp_username", models.CharField(max_length=50, null=True)),
                ("ftp_password", models.CharField(max_length=50, null=True)),
                ("host", models.CharField(max_length=255)),
                ("apiAccessId", models.CharField(max_length=255, null=True)),
                ("apiAccessKey", models.CharField(max_length=255, null=True)),
                ("Username", models.CharField(max_length=255, null=True)),
                ("Password", models.CharField(max_length=255, null=True)),
                ("POS", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorActivities.vendors",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "percentage_markup",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "fixed_markup",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("shipping_cost_average", models.BooleanField(default=False)),
                ("stock_minimum", models.PositiveIntegerField(default=0, null=True)),
                ("stock_maximum", models.PositiveIntegerField(default=0, null=True)),
                ("update_inventory", models.BooleanField(default=False)),
                ("send_orders", models.BooleanField(default=False)),
                ("update_tracking", models.BooleanField(default=False)),
                (
                    "product_filter",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "product_category",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("brand", models.JSONField(blank=True, default=list, null=True)),
                ("manufacturer", models.JSONField(blank=True, default=list, null=True)),
                ("shippable", models.JSONField(blank=True, default=list, null=True)),
                ("serialized", models.BooleanField(default=False)),
                ("truck_freight", models.BooleanField(default=False)),
                ("oversized", models.BooleanField(default=False)),
                ("third_party_marketplaces", models.BooleanField(default=False)),
                ("returnable", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="vendorEnrollment.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorActivities.vendors",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CwrUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=255, null=True)),
                ("upc", models.CharField(blank=True, max_length=255, null=True)),
                ("mpn", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorEnrollment.account",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorActivities.cwr",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorActivities.vendors",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorEnrollment.enrollment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BackgroundTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
                ("result", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorEnrollment.enrollment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FragrancexUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=255, null=True)),
                ("upc", models.CharField(blank=True, max_length=255, null=True)),
                ("mpn", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorEnrollment.account",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorEnrollment.enrollment",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorActivities.fragrancex",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorActivities.vendors",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Generalproducttable",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_id", models.TextField(null=True)),
                ("vendor_name", models.CharField(max_length=255, null=True)),
                (
                    "sku",
                    models.CharField(
                        blank=True, db_column="SKU", max_length=255, null=True
                    ),
                ),
                (
                    "quantity",
                    models.TextField(blank=True, db_column="Quantity", null=True),
                ),
                (
                    "upc",
                    models.CharField(
                        blank=True, db_column="UPC", max_length=255, null=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, db_column="Title", max_length=255, null=True
                    ),
                ),
                (
                    "detailed_description",
                    models.TextField(
                        blank=True, db_column="Detailed_Description", null=True
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        blank=True, db_column="Image", max_length=255, null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, db_column="Category", max_length=255, null=True
                    ),
                ),
                (
                    "category_id",
                    models.IntegerField(blank=True, db_column="Category_ID", null=True),
                ),
                ("msrp", models.TextField(blank=True, db_column="MSRP", null=True)),
                (
                    "mpn",
                    models.CharField(
                        blank=True, db_column="MPN", max_length=255, null=True
                    ),
                ),
                ("map", models.TextField(blank=True, db_column="MAP", null=True)),
                (
                    "dimensionh",
                    models.DecimalField(
                        blank=True,
                        db_column="DimensionH",
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "dimensionl",
                    models.DecimalField(
                        blank=True,
                        db_column="DimensionL",
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "dimensionw",
                    models.DecimalField(
                        blank=True,
                        db_column="DimensionW",
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "shipping_weight",
                    models.DecimalField(
                        blank=True,
                        db_column="Shipping_Weight",
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "shipping_length",
                    models.DecimalField(
                        blank=True,
                        db_column="Shipping_Length",
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "shipping_width",
                    models.DecimalField(
                        blank=True,
                        db_column="Shipping_Width",
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "shipping_height",
                    models.TextField(
                        blank=True, db_column="Shipping_Height", null=True
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, db_column="Model", max_length=255, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        db_column="Price",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, db_column="Brand", max_length=255, null=True
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, db_column="Manufacturer", max_length=255, null=True
                    ),
                ),
                (
                    "prop_65",
                    models.IntegerField(blank=True, db_column="Prop_65", null=True),
                ),
                (
                    "prop_65_description",
                    models.TextField(
                        blank=True, db_column="Prop_65_Description", null=True
                    ),
                ),
                (
                    "manufacturer_id",
                    models.IntegerField(
                        blank=True, db_column="Manufacturer_Id", null=True
                    ),
                ),
                (
                    "date_created",
                    models.DateField(blank=True, db_column="Date_Created", null=True),
                ),
                (
                    "thumbnail",
                    models.CharField(
                        blank=True, db_column="Thumbnail", max_length=255, null=True
                    ),
                ),
                (
                    "features",
                    models.TextField(blank=True, db_column="Features", null=True),
                ),
                ("active", models.BooleanField(default=False)),
                (
                    "total_product_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorEnrollment.enrollment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendorenrollment_generalproducts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LipseyUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=255, null=True)),
                ("upc", models.CharField(blank=True, max_length=255, null=True)),
                ("mpn", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorEnrollment.account",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorEnrollment.enrollment",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorActivities.lipsey",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorActivities.vendors",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RsrUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=255, null=True)),
                ("upc", models.CharField(blank=True, max_length=255, null=True)),
                ("mpn", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorEnrollment.account",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorEnrollment.enrollment",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorActivities.rsr",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorActivities.vendors",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SsiUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=255, null=True)),
                ("upc", models.CharField(blank=True, max_length=255, null=True)),
                ("mpn", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorEnrollment.account",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorEnrollment.enrollment",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorActivities.ssi",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorActivities.vendors",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ZandersUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=255, null=True)),
                ("upc", models.CharField(blank=True, max_length=255, null=True)),
                ("mpn", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorEnrollment.account",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorEnrollment.enrollment",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorActivities.zanders",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorActivities.vendors",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="unique_account_per_user"
            ),
        ),
    ]
