# Generated by Django 5.0.1 on 2026-04-02 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorActivities', '0005_vendors_api_details_vendors_description_and_more'),
        ('vendorEnrollment', '0004_cwrupdate_msrp_fragrancexupdate_msrp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssiupdate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorActivities.ssi'),
        ),
    ]
