# Generated by Django 5.0.1 on 2026-04-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorEnrollment', '0005_alter_ssiupdate_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='identifier',
            field=models.CharField(max_length=255),
        ),
    ]
