# Generated by Django 5.0.1 on 2026-04-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorEnrollment', '0007_enrollment_adult_sig_threshold_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeldSku',
        ),
    ]
