# Generated by Django 5.2.3 on 2025-06-27 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendorEnrollment", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("location", models.TextField(null=True)),
                ("category_id", models.TextField()),
                ("sku", models.CharField(max_length=25)),
                ("upc", models.CharField(max_length=25)),
                ("start_price", models.TextField()),
                ("picture_detail", models.TextField()),
                ("postal_code", models.TextField(null=True)),
                ("quantity", models.TextField()),
                ("return_profileID", models.TextField()),
                ("return_profileName", models.TextField()),
                ("payment_profileID", models.TextField()),
                ("payment_profileName", models.TextField()),
                ("shipping_profileID", models.TextField()),
                ("shipping_profileName", models.TextField()),
                ("bestOfferEnabled", models.BooleanField(null=True)),
                ("listingType", models.TextField(null=True)),
                ("gift", models.BooleanField(null=True)),
                ("categoryMappingAllowed", models.BooleanField(null=True)),
                ("item_specific_fields", models.TextField()),
                ("market_logos", models.TextField(null=True)),
                ("ebay_item_id", models.CharField(max_length=20, null=True)),
                ("map_status", models.BooleanField(default=False)),
                ("date_created", models.DateField(auto_now_add=True, null=True)),
                ("active", models.BooleanField(default=False)),
                ("enable_charity", models.BooleanField(default=False)),
                ("category", models.CharField(max_length=100, null=True)),
                ("city", models.CharField(max_length=20, null=True)),
                ("cost", models.CharField(max_length=20, null=True)),
                ("country", models.CharField(max_length=20, null=True)),
                ("model", models.CharField(max_length=20, null=True)),
                ("msrp", models.CharField(max_length=20, null=True)),
                ("price", models.CharField(max_length=20, null=True)),
                ("percentage_markup", models.CharField(max_length=20, null=True)),
                ("fixed_markup", models.TextField(null=True)),
                ("shipping_cost", models.CharField(max_length=20, null=True)),
                ("shipping_height", models.CharField(max_length=20, null=True)),
                ("shipping_width", models.CharField(max_length=20, null=True)),
                ("thumbnailImage", models.TextField(null=True)),
                ("total_product_cost", models.CharField(max_length=20, null=True)),
                ("us_size", models.CharField(max_length=20, null=True)),
                ("min_profit_mergin", models.FloatField(null=True)),
                ("profit_margin", models.FloatField(null=True)),
                ("charity_id", models.BigIntegerField(null=True)),
                ("donation_percentage", models.IntegerField(null=True)),
                ("vendor_name", models.TextField(null=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorEnrollment.generalproducttable",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
