from django.db import models
from accounts.models import User
from vendorEnrollment.models import Generalproducttable

# Create your models here.
class InventoryModel(models.Model):
    title = models.TextField(null=False, unique=False)
    description = models.TextField(null=False, unique=False)
    location = models.TextField(null=True, unique=False)
    category_id = models.TextField(null=False, unique=False)
    sku = models.CharField(null=False, unique=False, max_length=25)
    upc = models.CharField(null=False, unique=False, max_length=25)
    start_price = models.TextField(null=False, unique=False)
    picture_detail = models.TextField(null=False, unique=False)
    postal_code = models.TextField(null=True, unique=False)
    quantity = models.TextField(null=False, unique=False)
    return_profileID = models.TextField(null=False, unique=False)
    return_profileName = models.TextField(null=False, unique=False)
    payment_profileID = models.TextField(null=False, unique=False)
    payment_profileName = models.TextField(null=False, unique=False)
    shipping_profileID = models.TextField(null=False, unique=False)
    shipping_profileName = models.TextField(null=False, unique=False)
    bestOfferEnabled = models.BooleanField(null=True, unique=False)
    listingType = models.TextField(null=True, unique=False)
    gift = models.BooleanField(null=True, unique=False)
    categoryMappingAllowed = models.BooleanField(null=True, unique=False)
    item_specific_fields = models.TextField(null=False, unique=False)
    market_logos = models.TextField(null=True, unique=False)
    ebay_item_id = models.CharField(null=True, unique=False, max_length=20)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Generalproducttable, on_delete=models.CASCADE, null=True)
    map_status = models.BooleanField(default=False, unique=False)
    date_created = models.DateField(auto_now_add=True, unique=False, null=True)
    active = models.BooleanField(default=False, unique=False)
    enable_charity = models.BooleanField(default=False, unique=False)
    category = models.CharField(null=True, unique=False, max_length=100)
    city = models.CharField(null=True, unique=False, max_length=20)
    cost = models.CharField(null=True, unique=False, max_length=20)
    country = models.CharField(null=True, unique=False, max_length=20)
    model = models.CharField(null=True, unique=False, max_length=20)
    msrp = models.CharField(null=True, unique=False, max_length=20)
    price = models.CharField(null=True, unique=False, max_length=20)
    percentage_markup = models.CharField(null=True, unique=False, max_length=20)
    fixed_markup = models.TextField(null=True, unique=False)
    shipping_cost = models.CharField(null=True, unique=False, max_length=20)
    shipping_height = models.CharField(null=True, unique=False, max_length=20)
    shipping_width = models.CharField(null=True, unique=False, max_length=20)
    thumbnailImage = models.TextField(null=True, unique=False)
    total_product_cost = models.CharField(null=True, unique=False, max_length=20)
    us_size = models.CharField(null=True, unique=False, max_length=20)
    min_profit_mergin = models.FloatField(null=True, unique=False)
    profit_margin = models.FloatField(null=True, unique=False)
    charity_id = models.BigIntegerField(null=True, unique=False)
    donation_percentage = models.IntegerField(null=True, unique=False)
    vendor_name = models.TextField(null=True, unique=False)
    

