# Generated by Django 5.2.3 on 2025-06-27 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CancelOrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cancel_reason", models.CharField(max_length=155, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrdersOnEbayModel",
            fields=[
                ("_id", models.AutoField(primary_key=True, serialize=False)),
                ("orderId", models.CharField(max_length=155, unique=True)),
                ("legacyOrderId", models.CharField(max_length=155, unique=True)),
                ("creationDate", models.DateTimeField(null=True)),
                ("orderFulfillmentStatus", models.CharField(max_length=155)),
                ("orderPaymentStatus", models.CharField(max_length=155)),
                ("sellerId", models.CharField(max_length=155)),
                ("buyer", models.TextField(null=True)),
                ("cancelStatus", models.TextField(null=True)),
                ("pricingSummary", models.TextField(null=True)),
                ("paymentSummary", models.TextField(null=True)),
                ("fulfillmentStartInstructions", models.TextField(null=True)),
                ("sku", models.CharField(max_length=155)),
                ("title", models.CharField(max_length=155)),
                ("lineItemCost", models.CharField(max_length=155)),
                ("quantity", models.CharField(max_length=155)),
                ("listingMarketplaceId", models.CharField(max_length=155)),
                ("purchaseMarketplaceId", models.CharField(max_length=155)),
                ("itemLocation", models.TextField(null=True)),
                ("image", models.TextField(null=True)),
                ("additionalImages", models.TextField(null=True)),
                ("mpn", models.CharField(max_length=155, null=True)),
                ("description", models.TextField(null=True)),
                ("categoryId", models.CharField(max_length=155, null=True)),
                ("vendor_name", models.CharField(max_length=155, null=True)),
                ("tracking_id", models.CharField(max_length=155, null=True)),
                ("ebayItemId", models.CharField(max_length=155, null=True)),
                ("itemEbayStatus", models.CharField(max_length=155, null=True)),
                ("legacyItemId", models.TextField(null=True)),
                ("localizeAspects", models.CharField(max_length=155, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
