# Generated by Django 5.0.1 on 2026-04-02 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0009_vendororderlog_fulfillment_url'),
        ('vendorEnrollment', '0008_delete_heldsku'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeldSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_skus', to='vendorEnrollment.account')),
            ],
        ),
        migrations.AddConstraint(
            model_name='heldsku',
            constraint=models.UniqueConstraint(fields=('account', 'sku'), name='unique_held_sku_per_account'),
        ),
    ]
