# Generated by Django 5.2.3 on 2025-06-27 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendorEnrollment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorizationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authorization_code", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MarketplaceEnronment",
            fields=[
                ("_id", models.AutoField(primary_key=True, serialize=False)),
                ("marketplace_name", models.CharField(max_length=50, null=True)),
                ("region", models.CharField(max_length=50, null=True)),
                ("store_id", models.TextField(null=True)),
                ("store_logo", models.TextField(null=True)),
                ("fixed_percentage_markup", models.TextField(null=True)),
                ("fixed_markup", models.TextField(null=True)),
                ("enable_price_update", models.BooleanField(null=True)),
                ("enable_quantity_update", models.BooleanField(null=True)),
                ("maximum_quantity", models.TextField(null=True)),
                ("enable_charity", models.BooleanField(null=True)),
                ("charity_id", models.BigIntegerField(null=True)),
                ("donation_percentage", models.IntegerField(null=True)),
                ("enable_best_offer", models.BooleanField(null=True)),
                ("RIO_strategy", models.TextField(null=True)),
                ("min_profit_mergin", models.FloatField(null=True)),
                ("profit_margin", models.FloatField(null=True)),
                ("send_min_price", models.BooleanField(null=True)),
                ("warn_copyright_complaints", models.BooleanField(null=True)),
                ("warn_restriction_violation", models.BooleanField(null=True)),
                ("shipping_policy", models.TextField(null=True)),
                ("return_policy", models.TextField(null=True)),
                ("payment_policy", models.TextField(null=True)),
                ("refresh_token", models.TextField()),
                ("access_token", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UploadedProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.ImageField(upload_to="productImage/")),
                ("image_name", models.CharField(max_length=100)),
                ("uploaded_date", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendorEnrollment.generalproducttable",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
